geopocos/core/urls.py
from django.urls import path

from . import views as v

app_name = 'core'

urlpatterns = [
    path('', v.index, name='index'),
    path('mapa/', v.mapa, name='mapa'),
]

geopocos/poco/urls.py
from django.urls import path

from . import views as v

app_name = 'poco'

urlpatterns = [
    path('geojson/', v.PocoGeoJson.as_view(), name='poco_geojson'),
    path('pocos.js/', v.pocos_js, name='pocos_js'),
]

geopocos/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('geopocos.core.urls')),
    path('pocos/', include('geopocos.poco.urls')),
    path('admin/', admin.site.urls),
]

geopocos/core/models.py
from django.db import models

# Create your models here.

geopocos/municipio/models.py
from django.contrib.gis.db import models


class Municipio(models.Model):
    nome = models.CharField('nome', max_length=40)
    cod_ibge_m = models.CharField('código IBGE', max_length=20)
    geom = models.MultiPolygonField('geom', srid=4326)

    def __str__(self):
        return self.nome

geopocos/poco/models.py
from django.contrib.gis.db import models
from django.template.defaultfilters import date


class Poco(models.Model):
    proprietario = models.CharField('proprietário', max_length=255, null=True, blank=True)
    orgao = models.CharField('órgão responsável', max_length=255, null=True, blank=True)
    data_perfuracao = models.DateField('data de perfuração', null=True, blank=True)
    profundidade = models.FloatField('profundidade (m)', null=True, blank=True)
    q_m3h = models.FloatField('vazão m3/h', null=True, blank=True)
    equipamento = models.CharField('equipamento', max_length=255, null=True, blank=True)
    geom = models.PointField('geom', srid=4326)

    def __str__(self):
        return self.proprietario

    @property
    def popup_content(self):
        popup = "<span>Proprietário: </span>{}".format(
            self.proprietario)
        popup += "<span>Órgão: </span>{}".format(
            self.orgao)
        popup += "<span>Data de Perfuração: </span>{}".format(
            date(self.data_perfuracao, "d/m/Y"))
        popup += "<span>Profundidade (m): </span>{}".format(
            self.profundidade)
        popup += "<span>Vazão (m3/h): </span>{}".format(
            self.q_m3h)
        popup += "<span>Equipamento: </span>{}".format(
            self.equipamento)
        return popup

geopocos/core/views.py
from django.db.models import Max
from django.shortcuts import render

from geopocos.poco.models import Poco


def index(request):
    return render(request, 'core/index.html')


def mapa(request):
    q_max = Poco.objects.aggregate(Max('q_m3h'))

    context = {
        'q_max': q_max,
    }

    return render(request, 'core/mapa.html', context)

geopocos/municipio/views.py
from django.shortcuts import render

# Create your views here.

geopocos/poco/views.py
from django.shortcuts import render
from djgeojson.views import GeoJSONLayerView

from geopocos.poco.models import Poco


class PocoGeoJson(GeoJSONLayerView): # mostrar dados em formato json /pocos/geojson/
    model = Poco
    properties = ('popup_content',)


def pocos_js(request):
    pocos = Poco.objects.all()
    context = {
        'object_list': pocos,
    }
    return render(request, 'poco/poco_js.html', context)

geopocos/core/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Leaflet Routing Machine Example</title>
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.2.0/dist/leaflet.css" />
    <link rel="stylesheet" href="{% static 'routing/leaflet-routing-machine.css' %}">
    <style>
        .map {
            position: absolute;
            width: 100%;
            height: 100%;
        }
    </style>
</head>
<body>
    <div id="map" class="map"></div>
    <script src="https://unpkg.com/leaflet@1.2.0/dist/leaflet.js"></script>
    <script src="{% static 'routing/leaflet-routing-machine.js' %}"></script>
</body>

<script>
var map = L.map('map');

L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
    attribution: '© OpenStreetMap contributors'
}).addTo(map);

L.Routing.control({
    waypoints: [
        L.latLng(57.74, 11.94),
        L.latLng(57.6792, 11.949)
    ],
    routeWhileDragging: true
}).addTo(map);

for ( var i = 0; i < 9; i++) {
	L.Routing.control({
    waypoints: [
        L.latLng(62.74+i, 10.94+i),
        L.latLng(50.6792+i, 12.949+i)
    ],
    routeWhileDragging: true
    }).addTo(map);
}
</script>

</html>

geopocos/core/templates/core/index.html
{% extends 'base.html' %}


{% block content %}

    <div class="jumbotron mt-lg-5">
        <div class="container">
            <h1 class="display-3">GeoPoços</h1>
            <p>SIG-WEB com o objetivo de exibir os poços perfurados do Estado da Paraíba.</p>
            <p><a class="btn btn-primary btn-lg" href="{% url 'core:mapa' %}" role="button">
                Acessar o Mapa »</a>
            </p>
        </div>
    </div>

{% endblock content %}

geopocos/core/templates/core/mapa.html
{% extends 'base.html' %}
{% load static %}

{% block extra_css %}
    <link href="{% static 'libs/leaflet/leaflet.css' %}" rel="stylesheet">
{% endblock extra_css %}


{% block content %}
   <div id="map" class="map"></div>
{% endblock content %}


<script>
var map = L.map('map');

L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
    attribution: '© OpenStreetMap contributors'
}).addTo(map);

L.Routing.control({
    waypoints: [
        L.latLng(57.74, 11.94),
        L.latLng(57.6792, 11.949)
    ],
    routeWhileDragging: true
}).addTo(map);
</script>

{% block extra_js %}
    <script src="https://unpkg.com/leaflet@1.2.0/dist/leaflet.js"></script>
    <script src="{% static 'routing/leaflet-routing-machine.js' %}"></script>
    <script src="{% static 'libs/leaflet/leaflet.js' %}"></script>
    <script src="{% static 'libs/leaflet-heat/leaflet-heat.js' %}"></script>
    <script src="{% url 'poco:pocos_js' %}"></script>
    <script src="{% static 'js/map.js' %}"></script>
{% endblock extra_js %}

geopocos/core/templates/includes/navbar.html
<header>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="{% url 'core:index' %}">GeoPoços</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item {% if request.resolver_match.url_name == "index" %}active{% endif %}">
                    <a class="nav-link" href="{% url 'core:index' %}">Home</a>
                </li>
                <li class="nav-item {% if request.resolver_match.url_name == "mapa" %}active{% endif %}">
                    <a class="nav-link" href="{% url 'core:mapa' %}">Mapa</a>
                </li>
            </ul>
        </div>
    </nav>
</header>

geopocos/poco/templates/poco/poco_js.html
var pocosCoord = [

{% for poco in object_list %}
        [{{ poco.geom.y|safe }}, {{ poco.geom.x|safe }}, {{ poco.q_m3h|safe }}],
{% endfor %}

];